fix missing return code
src/pmi/upmi/upmi.c: In function 'UPMI_GET_LOCAL_RANK':
src/pmi/upmi/upmi.c:746:1: error: control reaches end of non-void function [-Werror=return-type]
  746 | }
      | ^
src/pmi/upmi/upmi.c: In function 'UPMI_GET_LOCAL_SIZE':
src/pmi/upmi/upmi.c:764:1: error: control reaches end of non-void function [-Werror=return-type]
  764 | }
      | ^
src/pmi/upmi/upmi.c: In function 'UPMI_GET_LOWEST_RANK':
src/pmi/upmi/upmi.c:782:1: error: control reaches end of non-void function [-Werror=return-type]
  782 | }

Signed-off-by: Nicolas Morey-Chaisemartin <nmoreychaisemartin@suse.com>